name: MCBOB
main: se.laeffe.mcbob.Mcbob
version: 0.0.1
commands:
  chteam:
    description: Changes team.
    usage: |
           /<command> [teamname] [playername]
  teamhome:
    description: Teleports to teamhome.
    usage: |
           /<command>
  battle:
    description: Sets or toggles battle state.
    usage: |
           /<command> [0|1]
  setperiod:
    description: Sets the period for build and battle modes. At least buildticks is required
    usage: |
           /<command> [buildticks] [battleticks]
  settime:
    description: Sets the time for build and battle modes. At least buildtime is required
    usage: |
           /<command> [buildticks] [battleticks]
  rebuildbases:
    description: Rebuild all bases
    usage: |
           /<command>
  startgame:
    description: Start a new McBob game in a world.
    usage: |
           /<command> [world]
  stopgame:
    description: Removes McBob game in a world.
    usage: |
           /<command> [world]
  createworld:
    description: Creates a new world.
    usage: |
           /<command> [world]
  removeworld:
    description: Removes a world.
    usage: |
           /<command> [world]
  tpworld:
    description: Teleport to world, and join game if any is running.
    usage: |
           /<command> [world]
  reloadconfig:
    description: Reloads config.
    usage: |
           /<command>
