global:
  radius: 100
  distance: 40
  battlePeriod: 300
  buildPeriod: 900
  notificationSeconds: 10
  notifyEvery: 30
  punishflagCarrierAfter: 30

worlds:
  world:
    battlePeriod: 150
    buildPeriod: 300
  