nogame:
  allowbuild: false
chatisolation:
  enable: true
  chatWithAllIndicator: !
global:
  radius: 300
  distance: 50
  battlePeriod: 600
  buildPeriod: 600
  firstBuildTime: 1200
  notificationSeconds: 10
  notifyEvery: 30
  punishflagCarrierAfter: 60
  spawn:
    respawntime: 10
    keepxp: true
  endcondition:
    nrOfFlips: 0
    maxSeconds: 3000
    winningScore: 0
    maxScore: 0
  teamChest:
    all:
      LOG: 64
      COBBLESTONE: 64
      SULPHUR: 64
      IRON_INGOT: 64
      TORCH: 64
      EGG: 64
      SAPLING: 16
    team:
      North:
        STONE: 1
      South:
        gravel: 1